version: '2'

services:
  _base:
    image: gradle:4.8.1-jdk8
    user: root
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
    working_dir: /app
    environment:
      DB_NAME: order
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: password

  dev:
    extends:
      service: _base

  api:
    extends:
      service: _base
    command: "gradle bootRun"
    environment:
      TERM: xterm
      FLYWAY_LOCATIONS: classpath:db/migration
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:9.5
    volumes:
      - ./support/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order
    ports:
      - "5432:5432"

volumes:
  gradle-cache:
