version: '2'

services:
  _base:
    image: gradle:4.8.1-jdk8
    user: root
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
    working_dir: /app

  dev:
    extends:
      service: _base

  api:
    extends:
      service: _base
    command: "gradle bootRun"
    environment:
      TERM: xterm
    ports:
      - "8080:8080"

volumes:
  gradle-cache:
