node {
    def app

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Test') {
        app.inside {
            sh 'echo "Tests passed"'
        }
    }

    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

        app.inside {
            sh 'echo "Build image passed"'
        }
    }

}